name: Flask application deploy on heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"


    - name: Install the dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip3 install flake8
        pip3 install pytest

    - name: Lint with flake8
      run: |
        # stop the build if syntax error
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run the test
      run: |
        export PYTHONPATH=src
        pytest

    - name: Deploy application on Heroku 
      env:  
        HEROKU_TOKEN: ${{secrets.HEROKU_API_TOKEN}}
        APP_NAME: ${{secrets.HEROKU_APP_NAME}}

      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:master -f